#!/bin/bash

# get the directory this file is in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

Help()
{
    echo "sync the project assets with google drive"
    echo
    echo "Syntax: sync [-d|u]"
    echo "Options:"
    echo "h        print this help"
    echo "u        sync \"up\" from local drive to google drive"
    echo "d        sync \"down\" from google drive to local drive"
    echo "c        Check if the files in source and destination match"   
}

CheckStatus()
{
    # Check if the files in source and destination match
    rclone check wasteland-warrior:assets project/assets

}

SyncDown()
{
    # Sync assets from the server to the local machine
    rclone sync --interactive wasteland-warrior:assets $DIR/project/assets;$SHELL
}

SyncUp()
{
    # Sync assets from the server to the local machine
    rclone sync --interactive $DIR/project/assets wasteland-warrior:assets;$SHELL
}

if [ -z "$1" ] 
    then Help
    exit 1
fi

while getopts ":hduc" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      u) #upload
         SyncUp
         exit;;
      d) #download
         SyncDown
         exit;;
      c) #check
         CheckStatus
         exit;;
     \?) # Invalid option
         echo "Error: Invalid option"
         echo "use -h for a list of options"
         exit;;
   esac
done